### ISSUE TITLE
Feature to avoid overwriting of existing tags

### ISSUE THREAD

**Issue by cjmeenu88** [GorillaStack/auto-tag#17] opened 2017-04-17 14:43 UTC
The tags created either adds or overwrites tags to a resource. It would be great if we add tags only if they do not exist.  This would help to avoid tags being overwritten by AutoTag.  
We need this feature as we want to retain tags like ProductID where user assigned values can be different from the value assigned by AutoTag .

**Comment by em0ney** [comment] 2017-06-30 03:52
The autotag solution should not be removing any tags on your existing resources.

Did you experience this happening?  Can you share which resource type it was on?  And give me a few steps to re-produce

**Comment by em0ney** [comment] 2018-02-27 04:36
@cjmeenu88 - closing for now.  please get back to me with more information if you come back, because I have not been able to reproduce and this should not happen

**Closed by em0ney** 2018-02-27 04:36 UTC
