### ISSUE TITLE
Failing to launch stack

### ISSUE THREAD

**Issue by deejanu** [GorillaStack/auto-tag#3] opened 2016-05-10 20:20 UTC
It is failing to launch stack with this error:

Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.

AWS::Lambda::Function
AutoTagLambdaFunction

**Comment by em0ney** [comment] 2016-05-10 23:22
Hey there @deejanu,

Looks like it is having trouble finding the code s3 bucket for the AutoTag code.
Can you please let me know the following:

* What region are you trying to launch the stack in
* All the settings for the CloudFormation stack, namely:
** The stack name
** Each of the parameters

Thanks,
Elliott

**Comment by deejanu** [comment] 2016-05-11 02:51
I'm launching the stack in us-west-2.
Stack Name: autotag
Trail: qez-autotag
Bucket: qez-autotag-us-west-2

**Comment by MaheshBeri** [comment] 2016-05-11 04:04
@em0ney  - Just as feedback I launched into ap-northeast-1. 
The stack completed successfully. Tagging is working most cases, yet I get "Cannot read property 'instancesSet' of null"," in logs. Maybe a separate issue, I will create.

**Comment by em0ney** [comment] 2016-05-11 04:08
Hi @deejanu,

The issue is with the setting for the 'CodeS3Bucket'.  We are hosting the latest version of autotag in each region in a bucket matching the pattern `gorillastack-autotag-releases-${regionId}`.

Please set your parameters as follows:

    CloudTrailBucketName: <some unique name>,
    CodeS3Bucket: gorillastack-autotag-releases-us-west-2,
    CodeS3Path: autotag-0.3.0.zip

**Comment by deejanu** [comment] 2016-05-12 16:07
The stack got created after I corrected CodeS3Bucket. Tagging seems to be working on EC2 instances and creating this tag:

Key:  AutoTag_Creator
Value:  arn:aws:iam::1234567890:user/tester

**Comment by em0ney** [comment] 2018-02-27 02:17
Great - happy this is working for you now.  Closing

**Closed by em0ney** 2018-02-27 02:17 UTC
